version: 2
updates:

  - package-ecosystem: "docker"
    directory: "/"
    # directories: 
    #   - "/"
    #   - "/ip"
    #   - "/quic"
    #   - "/stable"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"
      include: "scope"
