name: Build Stable Docker Image CI

on:
  push:
    branches: [ main ]
    paths:
    - 'stable/Dockerfile'
  pull_request:
    branches: [ main ]
    paths:
    - 'stable/Dockerfile'
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: peytonyip/nginx-brotli

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@9614fae9e5c5eddabb09f90a270fcb487c9f7149 #v2.6.0
        with:
          cosign-release: 'v1.11.0'
      
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

      # 获得 Nginx 版本号
      - name: Set nginx version
        id: set-nginx-version
        run: |
          echo "NGINX-VERSION=$(head -n 1 ./stable/Dockerfile |awk -F '[=]'  '{print $2}')" >>  $GITHUB_OUTPUT
          echo "Nginx=$(head -n 1 ./stable/Dockerfile |awk -F '[=]'  '{print $2}')" 
          
      - name: Login to registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Login to Quay.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
      
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56
        with:
          context: .
          file: ./stable/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            peytonyip/nginx-brotli:stable
            peytonyip/nginx-brotli:${{ steps.set-nginx-version.outputs.NGINX-VERSION }}
            quay.io/yevision/nginx-brotli:stable
            quay.io/yevision/nginx-brotli:${{ steps.set-nginx-version.outputs.NGINX-VERSION }}
          #labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Sign the resulting Docker image digest except on PRs.
      # This will only write to the public Rekor transparency log when the Docker
      # repository is public to avoid leaking data.  If you would like to publish
      # transparency data even for private images, pass --force to cosign below.
      # https://github.com/sigstore/cosign
      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          COSIGN_EXPERIMENTAL: "true"
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: echo "${{ steps.meta.outputs.tags }}" | xargs -I {} cosign sign {}@${{ steps.build-and-push.outputs.digest }}

