name: Build Stable Docker Image CI

on:
  push:
    branches: [ main ]
    paths:
    - 'stable/Dockerfile'
  pull_request:
    branches: [ main ]
    paths:
    - 'stable/Dockerfile'
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: peytonyip/nginx-brotli

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@dd6b2e2b610a11fd73dd187a43d57cc1394e35f9 #v2.6.0
        with:
          cosign-release: 'v1.11.0'
      
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@6a58db7e0d21ca03e6c44877909e80e45217eed2

      # 获得 Nginx 版本号
      - name: Set nginx version
        id: set-nginx-version
        run: |
          echo "NGINX-VERSION=$(head -n 1 ./stable/Dockerfile |awk -F '[=]'  '{print $2}')" >>  $GITHUB_OUTPUT
          echo "Nginx=$(head -n 1 ./stable/Dockerfile |awk -F '[=]'  '{print $2}')" 
          
      - name: Login to registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Login to Quay.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
      
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./stable/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            peytonyip/nginx-brotli:stable
            peytonyip/nginx-brotli:${{ steps.set-nginx-version.outputs.NGINX-VERSION }}
            quay.io/yevision/nginx-brotli:stable
            quay.io/yevision/nginx-brotli:${{ steps.set-nginx-version.outputs.NGINX-VERSION }}
          #labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Sign the resulting Docker image digest except on PRs.
      # This will only write to the public Rekor transparency log when the Docker
      # repository is public to avoid leaking data.  If you would like to publish
      # transparency data even for private images, pass --force to cosign below.
      # https://github.com/sigstore/cosign
      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          COSIGN_EXPERIMENTAL: "true"
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: echo "${{ steps.meta.outputs.tags }}" | xargs -I {} cosign sign {}@${{ steps.build-and-push.outputs.digest }}

