name: Trivy
on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches: [ "main" ]
  schedule:
    - cron: '00 12 * * *'
  workflow_dispatch:

jobs:
  trivy-fs:
    name: Trivy FS Scan
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-fs.sarif'
          severity: 'CRITICAL'
          
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-fs.sarif'

  
  trivy-image:
    name: Trivy Image Scan
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      security-events: write
      actions: read
    strategy:
      matrix:
        image:
          - peytonyip/nginx-brotli:ip2location
          - peytonyip/nginx-brotli:zstd
          - peytonyip/nginx-brotli:ip2region
          - peytonyip/nginx-brotli:stable
          - peytonyip/nginx-brotli:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7



      # - name: Generate tarball from image
      #   run: |
      #     set -euxo pipefail
      #     docker pull peytonyip/nginx-brotli:latest
      #     docker save -o vuln-image.tar peytonyip/nginx-brotli:latest
      #     ls -lh "${{ github.workspace }}"/vuln-image.tar

      # - name: Run Trivy vulnerability scanner in tarball mode
      #   uses: aquasecurity/trivy-action@v0.36.0
      #   with:
      #     input: ${{ github.workspace }}/vuln-image.tar
      #     severity: 'CRITICAL,HIGH'
      #     format: 'sarif'
      #     output: 'trivy-image.sarif'
      - name: Sanitize image name
        id: vars
        run: |
          IMAGE_NAME=$(echo "${{ matrix.image }}" | sed 's#[/:]#-#g')
          echo "image_name=${IMAGE_NAME}" >> $GITHUB_OUTPUT

      - name: Run Trivy Image scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          # image-ref: peytonyip/nginx-brotli:latest
          image-ref: ${{ matrix.image }}
          ignore-unfixed: true
          severity: CRITICAL,HIGH
          format: sarif
          output: trivy-${{ steps.vars.outputs.image_name }}.sarif
      
      - name: Upload Image SARIF
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-${{ steps.vars.outputs.image_name }}.sarif'
          category: trivy-image-${{ steps.vars.outputs.image_name }}
